config/routes.rb
Rails.application.routes.draw do
  # ルートURLへのリクエストをWelcomeコントローラーのindexアクションにルーティング
  root 'welcome#index'
  
  get 'chat_room', to: 'chat_room#index', as: 'chat_room'
  get 'share_room', to: 'share_room#index', as: 'share_room'

  post 'chat_room/generate_plan', to: 'chat_room#generate_plan', as: 'generate_plan'

  # 生成結果ページのルート
  get 'chat_room/generate_plan_result', to: 'chat_room#generate_plan_result' , as: 'generate_plan_result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_room_controller.rb
# app/controllers/chat_room_controller.rb
require_relative '../services/gemini_travel_plan_generator.rb'
require_relative '../services/yolp_map_handler.rb'

class ChatRoomController < ApplicationController
  def index
  end
  
  def generate_plan
    # フォームから送られたパラメータを取得
    departure = params[:departure]
    destination = params[:destination]
    budget = params[:budget]
    nights = params[:nights]
    other = params[:other]
  
    # 旅行計画を生成するメソッドを呼び出し
    response = generate_travel_plan(departure, destination, budget, nights, other)
    puts response if response
    total_fee = 0
    response["plan"].each do |point|
      total_fee += point["fee"].to_i
    end
    description = response["description"]
    plan = response["plan"]
    redirect_to generate_plan_result_path(description: URI.encode_www_form_component(description), plan: plan, total_fee: total_fee)
  end

  def generate_plan_result
    @description = URI.decode_www_form_component(params["description"])
    @plan = params["plan"]
    @total_fee = params["total_fee"]
    
    # for display map (send to JS)
    # すべてのstart_pointとgoal_pointを一つの集合として取得し、重複要素を削除して順番を保持する
    places = @plan.flat_map { |point| [point["start_point"], point["goal_point"]] }.uniq
    waypoints = []
    places.each do |point|
      response = contents_geocoder(point)
      next if response.nil?
      
      name = response[:Name][:text] 
      coordinates = response[:Geometry][:Coordinates][:text].split(',')

      waypoints << { 
        name: name,
        latitude: coordinates[0].to_f,
        longitude: coordinates[1].to_f
      }
    end
    gon.waypoints = waypoints
  end

  private
  
  def ai_handler
    @ai_handler ||= GeminiTravelPlanGenerator.new 
  end
  
  def map_handler
    @map_handler ||= YolpMapHandler.new
  end

  def generate_travel_plan(departure, destination, budget, nights, other)
    ai_handler.generate_plan(departure, destination, budget, nights, other)
  end

  def contents_geocoder(query)
    map_handler.contents_geocoder(query)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_room_helper.rb
module ChatRoomHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chat_room/generate_plan_result.html.erb
<!DOCTYPE html>
<html lang="ja" dir="ltr">
<head>
  <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin="">
  <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
  <style media="screen">
    #mapid {
      height: 500px;
      width: 50%;
      margin-right: 25%; /* 右側に25%の余白を持たせる */
    }
  </style>
  <%= include_gon %>
  <%= javascript_include_tag 'controllers/leaflet_map.js' %>
</head>
<body>
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% else %>
  <h1>Travel Plan Result</h1>

  <div id="planResult">
    <!-- 整形された形で表示 -->
    <h1>生成結果：<%= @description %></h1>
    <p><%= @plan %></p>
    <p>料金：<%= @total_fee %></p>
  </div>
  
  <div id="mapid"></div>

  <div class="regenerate-plan">
    <%= link_to 'ルートを再生成する', chat_room_path %>
  </div>
<% end %>
</body>
</html>

app/views/chat_room/index.html.erb
<!-- index.html.erb -->
<!DOCTYPE html>

<html>
  <head>
      <%= stylesheet_link_tag 'chat_room', media: 'all' %>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
      <%= javascript_include_tag "chat_room.js" %>
  </head>
  <body>
    <div class = "chat_room pr">
      <div class = "chat_zone">
        <div class="chat-box">
          <div class="chat-face">
            <img src="/assets/Tabilog_kun.png" alt="自分のチャット画像です。" width="90" height="90">
          </div>
          <div class="chat-area">
            <div class="chat-hukidashi">
              旅行支援アプリ"Tabilog"へようこそ！！<br>
              ここではいくつかの質問に答えていただくだけで<br>
              あなたに旅行プランを提案致します！！<br>
              早速、最初の質問なのですが、出発地は何処でしょうか？？
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="talk_departure">
          <div class ="chat-contents">
            <div class="chat-area reflect">
              <div class="chat-hukidashi-r reflect">
                出発地
              </div>
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="question_destination">
          <div class="chat-face">
            <img src="/assets/Tabilog_kun.png" alt="自分のチャット画像です。" width="90" height="90">
          </div>
          <div class="chat-area">
            <div class="chat-hukidashi">
              ありがとうございます。続いての質問です！<br>
              旅行の目的地は何処でしょうか？？
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="talk_destination">
          <div class ="chat-contents">
            <div class="chat-area reflect">
              <div class="chat-hukidashi-r reflect">
                目的地
              </div>
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="question_budget">
          <div class="chat-face">
            <img src="/assets/Tabilog_kun.png" alt="自分のチャット画像です。" width="90" height="90">
          </div>
          <div class="chat-area">
            <div class="chat-hukidashi">
              ありがとうございます。続いての質問です！<br>
              旅行の予算はいくらでお考えですか？？
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="talk_budget">
          <div class ="chat-contents">
            <div class="chat-area reflect">
              <div class="chat-hukidashi-r reflect">
                予算
              </div>
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="question_nights">
          <div class="chat-face">
            <img src="/assets/Tabilog_kun.png" alt="自分のチャット画像です。" width="90" height="90">
          </div>
          <div class="chat-area">
            <div class="chat-hukidashi">
              ありがとうございます。続いての質問です！<br>
              何泊のご予定でしょうか？？
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="talk_nights">
          <div class ="chat-contents">
            <div class="chat-area reflect">
              <div class="chat-hukidashi-r reflect">
                泊数
              </div>
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="question_other">
          <div class="chat-face">
            <img src="/assets/Tabilog_kun.png" alt="自分のチャット画像です。" width="90" height="90">
          </div>
          <div class="chat-area">
            <div class="chat-hukidashi">
              その他、旅行計画に組み込んでほしい事があれば教えてください。<br>
              (ない場合には'なし'とご入力ください)
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="talk_other">
          <div class ="chat-contents">
            <div class="chat-area reflect">
              <div class="chat-hukidashi-r reflect">
                その他
              </div>
            </div>
          </div>
        </div>

        <div class="chat-box hidden" id="generate_plan">
          <div class="chat-face">
            <img src="/assets/Tabilog_kun.png" alt="自分のチャット画像です。" width="90" height="90">
          </div>
          <div class="chat-area">
            <div class="chat-hukidashi">
              <div>
                以上で質問は終了です。<br>
                生成結果を表示させたい場合は以下のボタンを押して生成してください。
              </div>
              <%= form_with(url: generate_plan_path, method: 'post', id: 'travelPlanForm', class: 'form') do |f| %>
                <!-- フォームの各入力フィールド -->
                <div class="form__control form__control--short hidden">
                  <%= f.label :departure, class: 'form__label' %>
                  <%= f.text_field :departure, value: 'Hokkaido', class: 'form__input', id: 'chat_departure', required: true %><br><br>
                </div>

                <div class="form__control form__control--short hidden">
                  <%= f.label :destination, class: 'form__label' %>
                  <%= f.text_field :destination, value: 'Osaka', class: 'form__input', id: 'chat_destination', required: true %><br><br>
                </div>

                <div class="form__control form__control--short hidden">
                  <%= f.label :budget, class: 'form__label' %>
                  <%= f.number_field :budget, value: 50000, class: 'form__input', id: 'chat_budget', required: true %><br><br>
                </div>

                <div class="form__control form__control--short hidden">
                  <%= f.label :nights, class: 'form__label' %>
                  <%= f.text_field :nights, value: '2', class: 'form__input', id: 'chat_nights', required: true %><br><br>
                </div>

                <div class="form__control form__control--short hidden">
                  <%= f.label :other, class: 'form__label' %>
                  <%= f.text_field :other, value: 'Sightseeing', class: 'form__input', id: 'chat_other', required: true %><br><br>
                </div>

                <!-- 旅行計画生成ボタン -->
                <%= f.submit '生成結果を表示', class: 'button button--primary generate_button', id: 'generateButton' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      
      <div class = "textbox_contents pa">
          <textarea class = "input-box" placeholder = "メッセージを入力してください"></textarea>
          <button class = "btn">
              <img src = "/assets/plane.png">
          </button>
      </div>
    </div>
    <div id="errorMessage" style="color: red; margin-top: 10px;"></div>
  </body>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      document.querySelector('#travelPlanForm').addEventListener('submit', function() {
        document.querySelector('#generateButton').setAttribute('disabled', 'disabled');
        document.querySelector('#generateButton').value = 'Generating...';
      });
    });
  </script> 
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabilog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap" rel="stylesheet">
</head>
<body>
  <% unless current_page?(root_path) %> 
    <%= render "shared/header" %>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/shared/_header.html.erb
<!-- app/views/shared/header.html.erb -->
<header>
    <p class="header-title">Tabilog</p>
    <nav>
        <ul>
            <!-- <li><%= link_to 'Home', root_path %></li> -->
            <li><%= link_to image_tag('icon-house.png'), root_path %></li>
        </ul>
    </nav>
</header>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Welcome to Tabilog</title>
    <%= stylesheet_link_tag 'welcome_styles', media: 'all' %>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Grape+Nuts&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <main>
      <section class="welcome-wrapper">
        <div class="welcome-container">
          <%= image_tag 'fv.jpg', class: "fv-image" %>
        </div>
        <div class="link-container">
          <%= link_to 'CHAT', chat_room_path, class: 'link-btn' %>
          <a class="link-btn" href="">SHARE</a>
          <!-- <%= link_to 'SHARE', share_room_path, class: 'btn' %> -->
        </div>
      </section>
    </main>
  </body>
</html>